name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into dir
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t brainyard/protoc:latest .
    - name: Docker Publish
      run: docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }} && docker push brainyard/protoc:latest
